POLISH_STOPWORDS = {
    "a", "aby", "abi", "ach", "acz", "aczkolwiek", "aj", "albo", "ale", "ależ", "ani", "aż", "bardziej", "bardzo", "bez",
    "bo", "bowiem", "by", "bi", "byli", "bili", "bym", "bim", "bynajmniej", "binajmniej", "być", "bić", "był", "bił", "była", "biła", "było", "biło", "były", "biłi", "będzie", "będą", "cali",
    "cała", "cały", "całi", "chce", "choć", "ci", "ciebie", "cię", "co", "cokolwiek", "coraz", "coś", "czasami", "czasem",
    "czemu", "czy", "czi", "czyli", "czili", "często", "daleko", "dla", "dlaczego", "dlatego", "do", "dobrze", "dokąd", "dość", "dr",
    "dużo", "dwa", "dwaj", "dwie", "dwoje", "dzisiaj", "dziś", "gdy", "gdi", "gdyby", "gdibi", "gdyż", "gdiż", "gdzie", "gdziekolwiek",
    "gdzieś", "go", "godz", "hab", "i", "ich", "ii", "iii", "ile", "im", "inna", "inne", "inny", "inni", "innych", "innich", "inż", "iv",
    "ix", "iż", "ja", "jak", "jakaś", "jakby", "jakbi", "jaki", "jakichś", "jakie", "jakiś", "jakiż", "jakkolwiek", "jako",
    "jakoś", "je", "jeden", "jedna", "jednak", "jednakże", "jedno", "jednym", "jednim", "jedynie", "jedinie", "jego", "jej", "jemu", "jest",
    "jestem", "jeszcze", "jeśli", "jeżeli", "już", "ją", "każdy", "każdi", "kiedy", "kiedi", "kierunku", "kilka", "kilku", "kimś", "kto",
    "ktokolwiek", "ktoś", "która", "które", "którego", "której", "który", "któri", "których", "którich", "którym", "którim", "którzy", "którzi", "ku", "lat",
    "lecz", "lub", "ma", "mają", "mam", "mamy", "mami", "mało", "mgr", "mi", "miał", "mimo", "między", "międzi", "mnie", "mną", "mogą",
    "moi", "moim", "moja", "moje", "może", "możliwe", "można", "mu", "musi", "my", "mi", "mój", "na", "nad", "nam", "nami",
    "nas", "nasi", "nasz", "nasza", "nasze", "naszego", "naszych", "naszich", "natomiast", "natychmiast", "natichmiast", "nawet", "nic", "nich",
    "nie", "niech", "niego", "niej", "niemu", "nigdy", "nigdi", "nim", "nimi", "nią", "niż", "no", "nowe", "np", "nr", "o",
    "o.o.", "obok", "od", "ok", "około", "on", "ona", "one", "oni", "ono", "oraz", "oto", "owszem", "pan", "pana",
    "pani", "pl", "po", "pod", "podczas", "pomimo", "ponad", "ponieważ", "powinien", "powinna", "powinni", "powinno",
    "poza", "prawie", "prof", "przecież", "przed", "przede", "przedtem", "przez", "przy", "przi", "raz", "razie", "roku",
    "również", "sam", "sama", "się", "skąd", "sobie", "sobą", "sposób", "swoje", "są", "ta", "tak", "taka", "taki",
    "takich", "takie", "także", "tam", "te", "tego", "tej", "tel", "temu", "ten", "teraz", "też", "to", "tobie", "tobą",
    "toteż", "totobą", "trzeba", "tu", "tutaj", "twoi", "twoim", "twoja", "twoje", "twym", "twim", "twój", "ty", "ti", "tych", "tich",
    "tylko", "tilko", "tym", "tim", "tys", "tis", "tzw", "tę", "u", "ul", "vi", "vii", "viii", "vol", "w", "wam", "wami", "was", "wasi",
    "wasz", "wasza", "wasze", "we", "według", "wie", "wiele", "wielu", "więc", "więcej", "wszyscy", "wszisci", "wszystkich", "wszistkich",
    "wszystkie", "wszistkie", "wszystkim", "wszistkim", "wszystko", "wtedy", "wtedi", "www", "wy", "wi", "właśnie", "wśród", "xi", "xii", "xiii", "xiv", "xv",
    "z", "za", "zapewne", "zawsze", "zaś", "ze", "zeznowu", "znowu", "znów", "został", "zł", "żaden", "żadna", "żadne",
    "żadnych", "żadnich", "że", "żeby", "żebi", "film", "filmi", "filmu", "praci", "obsada", "br"
}
